imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
