imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    #translator:      { fallback: "%locale_fallback%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
        # Note: changing this will break legacy extensions that rely on the default name to alter AJAX requests
        # See https://jira.ez.no/browse/EZP-20783
        field_name: ezxform_token
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['eztpl', 'twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale_fallback%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        # Note: eZ Publish also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading: https://doc.ez.no/display/EZP/Session+configuration
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ eZDemoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/../ezpublish_legacy

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
