doctrine:
    dbal:
        connections:
            default:
                driver: pdo_mysql
                host: localhost
                user: root
                dbname: behattestdb
                charset: UTF8

ezpublish:
    repositories:
        behat: ~
    siteaccess:
        # Available siteaccesses
        list:
            - behat_site
            - behat_site_admin
        # Siteaccess groups. Use them to group common settings.
        groups:
            behat_group: [behat_site, behat_site_admin]
        default_siteaccess: behat_site
        match:
            Map\URI:
                behat_site_admin: behat_site_admin
            Map\Host:
                localhost: behat_site
    system:
        behat_group:
            repository: behat
            languages: [eng-GB]
            var_dir: var/behat_site
        behat_site:
            legacy_mode: false
        behat_site_admin:
            legacy_mode: true

stash:
    caches:
        default:
            drivers: [ FileSystem ]
            inMemory: true
            registerDoctrineAdapter: false
