imports:
    -
        resource: ezpublish_behat.yml

doctrine:
    dbal:
        connections:
            default:
                driver: pdo_sqlite
                user: test
                password: test
                memory: true


ezpublish:
    system:
        behat_group:
            languages: [eng-GB, eng-US]
            var_dir: var/test_site

stash:
    caches:
        default:
            drivers: [ Ephemeral ]
            inMemory: false
            registerDoctrineAdapter: false
