security:
    providers:
        ezpublish:
            id: ezpublish.security.user_provider
#        in_memory:
#            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ezpublish_setup:
            pattern: ^/ezsetup
            security: false

        ezpublish_rest:
            pattern: ^/api/ezp/v2
            stateless: true
            ezpublish_http_basic:
                realm: eZ Publish REST API

        ezpublish_front:
            pattern: ^/
            anonymous: ~
            form_login:
                require_previous_session: false
            logout: ~

        default:
            anonymous: ~
