parameters:
    ezpublish.signalslot.service.tags.class: Netgen\TagsBundle\Core\SignalSlot\TagsService
    ezpublish.api.service.tags.inner.class: Netgen\TagsBundle\Core\Repository\TagsService

services:
    ezpublish.api.service.tags:
        alias: ezpublish.signalslot.service.tags

    ezpublish.signalslot.service.tags:
        class: %ezpublish.signalslot.service.tags.class%
        arguments:
            - @ezpublish.api.service.tags.inner
            - @ezpublish.signalslot.signal_dispatcher

    ezpublish.api.service.tags.inner:
        class: %ezpublish.api.service.tags.inner.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.api.persistence_handler.tags
