ezpublish:
    system:
        default:
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [120, 120] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [320, 320] }
                large:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [640, 640] }

    imagemagick:
        enabled: true
        path: /usr/bin/convert
        filters:
            geometry/scale: '-geometry {1}x{2}'
            geometry/scalewidth: '-geometry {1}'
            geometry/scaleheight: '-geometry x{1}'
            geometry/scaledownonly: '-geometry {1}x{2}>'
            geometry/scalewidthdownonly: '-geometry {1}>'
            geometry/scaleheightdownonly: '-geometry x{1}>'
            geometry/scaleexact: '-geometry {1}x{2}!'
            geometry/scalepercent: '-geometry {1}x{2}%'
            geometry/crop: '-crop {1}x{2}+{3}+{4}'
            filter/noise: '-noise {1}'
            filter/swirl: '-swirl {1}'
            colorspace/gray: '-colorspace GRAY'
            colorspace/transparent: '-colorspace Transparent'
            colorspace: '-colorspace {1}'
            border: '-border {1}x{2}'
            border/color: '-bordercolor rgb({1},{2},{3})'
            border/width: '-borderwidth {1}'
            flatten: -flatten
            resize: '-resize {1}'
