#register:
#    path:     /register
#    defaults: { _controller: CjwPublishToolsBundle:Formbuilder:userRegister }

#frontend_editing_edit:
#    pattern:  /content/edit/{locationid}
#    defaults: { _controller: CjwPublishToolsBundle:Formbuilder:editForm }
#frontend_editing_add:
#    pattern:  /content/add/{locationid}/{contenttypeid}
#    defaults: { _controller: CjwPublishToolsBundle:Formbuilder:addForm }
