<?php

namespace Cjw\PublishToolsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EzinfocollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EzinfocollectionRepository extends EntityRepository
{
}
